package com.bobbyesp.spowlo.utils

import android.database.sqlite.SQLiteDatabase
import android.util.Log
import android.webkit.CookieManager
import androidx.annotation.CheckResult
import com.bobbyesp.library.SpotDL
import com.bobbyesp.library.SpotDLRequest
import com.bobbyesp.library.domain.model.SpotifySong
import com.bobbyesp.library.util.exceptions.CanceledException
import com.bobbyesp.spowlo.App
import com.bobbyesp.spowlo.App.Companion.audioDownloadDir
import com.bobbyesp.spowlo.App.Companion.context
import com.bobbyesp.spowlo.Downloader
import com.bobbyesp.spowlo.R
import com.bobbyesp.spowlo.database.DownloadedSongInfo
import com.bobbyesp.spowlo.ui.pages.settings.cookies.Cookie
import com.bobbyesp.spowlo.utils.FilesUtil.getCookiesFile
import com.bobbyesp.spowlo.utils.FilesUtil.getSdcardTempDir
import com.bobbyesp.spowlo.utils.FilesUtil.moveFilesToSdcard
import com.bobbyesp.spowlo.utils.PreferencesUtil.getInt
import com.bobbyesp.spowlo.utils.PreferencesUtil.getString
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlin.math.roundToInt

object DownloaderUtil {

    private const val COOKIE_HEADER =
        "# Netscape HTTP Cookie File\n" + "# Auto-generated by Spowlo built-in WebView\n"

    private const val TAG = "DownloaderUtil"

    private val mutableSongsState = MutableStateFlow(listOf<SpotifySong>())
    val songsState = mutableSongsState.asStateFlow()

    data class DownloadPreferences(
        val downloadPlaylist: Boolean = PreferencesUtil.getValue(PLAYLIST),
        val customPath: Boolean = PreferencesUtil.getValue(CUSTOM_PATH),
        val maxFileSize: String = MAX_FILE_SIZE.getString(),
        val cookies: Boolean = PreferencesUtil.getValue(COOKIES),
        val cookiesContent: String = PreferencesUtil.getCookies(),
        val audioFormat: Int = PreferencesUtil.getAudioFormat(),
        val audioQuality: Int = PreferencesUtil.getAudioQuality(),
        val preserveOriginalAudio: Boolean = PreferencesUtil.getValue(ORIGINAL_AUDIO),
        val useSpotifyPreferences: Boolean = PreferencesUtil.getValue(USE_SPOTIFY_CREDENTIALS),
        val spotifyClientID: String = SPOTIFY_CLIENT_ID.getString(),
        val spotifyClientSecret: String = SPOTIFY_CLIENT_SECRET.getString(),
        val useYtMetadata: Boolean = PreferencesUtil.getValue(USE_YT_METADATA),
        val useCookies: Boolean = PreferencesUtil.getValue(COOKIES),
        val downloadLyrics: Boolean = PreferencesUtil.getValue(DOWNLOAD_LYRICS),
        val useCaching: Boolean = PreferencesUtil.getValue(USE_CACHING),
        val dontFilter: Boolean = PreferencesUtil.getValue(DONT_FILTER_RESULTS),
        val formatId: String = "",
        val incognitoMode: Boolean = PreferencesUtil.getValue(INCOGNITO_MODE),
        val sdcard: Boolean = PreferencesUtil.getValue(SDCARD_DOWNLOAD),
        val sdcardUri: String = SDCARD_URI.getString(),
        val extraDirectory: String = PreferencesUtil.getExtraDirectory(),
        val splitByMainArtist: Boolean = PreferencesUtil.getValue(SPLIT_BY_MAIN_ARTIST),
        val splitByPlaylist: Boolean = PreferencesUtil.getValue(SPLIT_BY_PLAYLIST),
        val threads: Int = THREADS.getInt(),
        val lyricProviders: String = LYRIC_PROVIDERS.getString(),
        val audioProviders: String = AUDIO_PROVIDERS.getString(),
        val sponsorBlock: Boolean = PreferencesUtil.getValue(SPONSORBLOCK),
        val onlyVerifiedResults: Boolean = PreferencesUtil.getValue(ONLY_VERIFIED_RESULTS),
        val skipExplicit: Boolean = PreferencesUtil.getValue(SKIP_EXPLICIT),
        val generateLRC: Boolean = PreferencesUtil.getValue(GENERATE_LRC),
        val skipAlbumArt: Boolean = PreferencesUtil.getValue(SKIP_ALBUM_ART),
        val outputFormat: String = OUTPUT_FORMAT.getString(),
    )

    private fun StringBuilder.buildPathExtensions(downloadPreferences: DownloadPreferences) {
        when {
            downloadPreferences.outputFormat.isNotEmpty() -> {
                this.append("/").append(downloadPreferences.outputFormat)
            }
            else -> return
        }
    }

    object CookieScheme {
        const val NAME = "name"
        const val VALUE = "value"
        const val SECURE = "is_secure"
        const val EXPIRY = "expires_utc"
        const val HOST = "host_key"
        const val PATH = "path"
    }

    fun getCookiesContentFromDatabase(): Result<String> = runCatching {
        CookieManager.getInstance().run {
            if (!hasCookies()) throw Exception("There is no cookies in the database!")
            flush()
        }
        SQLiteDatabase.openDatabase(
            "/data/data/com.bobbyesp.spowlo/app_webview/Default/Cookies",
            null,
            SQLiteDatabase.OPEN_READONLY
        ).run {
            val projection = arrayOf(
                CookieScheme.HOST,
                CookieScheme.EXPIRY,
                CookieScheme.PATH,
                CookieScheme.NAME,
                CookieScheme.VALUE,
                CookieScheme.SECURE
            )
            val cookieList = mutableListOf<Cookie>()
            query(
                "cookies", projection, null, null, null, null, null
            ).run {
                while (moveToNext()) {
                    val expiry = getLong(getColumnIndexOrThrow(CookieScheme.EXPIRY))
                    val name = getString(getColumnIndexOrThrow(CookieScheme.NAME))
                    val value = getString(getColumnIndexOrThrow(CookieScheme.VALUE))
                    val path = getString(getColumnIndexOrThrow(CookieScheme.PATH))
                    val secure = getLong(getColumnIndexOrThrow(CookieScheme.SECURE)) == 1L
                    val hostKey = getString(getColumnIndexOrThrow(CookieScheme.HOST))

                    val host = if (hostKey.isNotEmpty() && hostKey[0] != '.') ".$hostKey" else hostKey
                    cookieList.add(
                        Cookie(
                            domain = host,
                            name = name,
                            value = value,
                            path = path,
                            secure = secure,
                            expiry = expiry
                        )
                    )
                }
                close()
            }
            Log.d(TAG, "Loaded ${cookieList.size} cookies from database!")
            cookieList.fold(StringBuilder(COOKIE_HEADER)) { acc, cookie ->
                acc.append(cookie.toNetscapeCookieString()).append("\n")
            }.toString()
        }
    }
    
    fun updateSongsState(songs: List<SpotifySong>) {
        mutableSongsState.update { songs }
    }

    private fun SpotDLRequest.useCookies(): SpotDLRequest = this.apply {
        if (PreferencesUtil.getValue(COOKIES)) {
            addOption("--cookie-file", context.getCookiesFile().absolutePath)
        }
    }

    private fun SpotDLRequest.addAudioFormat(): SpotDLRequest = this.apply {
        when (PreferencesUtil.getAudioFormat()) {
            0 -> addOption("--format", "mp3")
            1 -> addOption("--format", "flac")
            2 -> addOption("--format", "ogg")
            3 -> addOption("--format", "opus")
            4 -> addOption("--format", "m4a")
            5 -> addOption("--format", "wav")
            6 -> Unit
        }
    }

    private fun SpotDLRequest.addAudioQuality(): SpotDLRequest = this.apply {
        when (PreferencesUtil.getAudioQuality()) {
            0 -> addOption("--bitrate", "auto")
            1 -> addOption("--bitrate", "8k")
            2 -> addOption("--bitrate", "16k")
            3 -> addOption("--bitrate", "24k")
            4 -> addOption("--bitrate", "32k")
            5 -> addOption("--bitrate", "40k")
            6 -> addOption("--bitrate", "48k")
            7 -> addOption("--bitrate", "64k")
            8 -> addOption("--bitrate", "80k")
            9 -> addOption("--bitrate", "96k")
            10 -> addOption("--bitrate", "112k")
            11 -> addOption("--bitrate", "128k")
            12 -> addOption("--bitrate", "160k")
            13 -> addOption("--bitrate", "192k")
            14 -> addOption("--bitrate", "224k")
            15 -> addOption("--bitrate", "256k")
            16 -> addOption("--bitrate", "320k")
            17 -> addOption("--bitrate", "disable")
        }
    }

    private fun SpotDLRequest.addAudioProvider(downloadPreferences: DownloadPreferences): SpotDLRequest =
        this.apply {
            if (downloadPreferences.audioProviders.isNotEmpty()) {
                addOption("--audio")
                if (downloadPreferences.audioProviders.contains("YouTube")) addOption("youtube")
                if (downloadPreferences.audioProviders.contains("YouTube Music")) addOption("youtube-music")
                if (downloadPreferences.audioProviders.contains("Soundcloud")) addOption("soundcloud")
                if (downloadPreferences.audioProviders.contains("Bandcamp")) addOption("bandcamp")
                if (downloadPreferences.audioProviders.contains("Piped")) addOption("piped")
            }
        }

    private fun createDownloadRequest(
        url: String,
        downloadPreferences: DownloadPreferences,
    ): SpotDLRequest {
        val request = SpotDLRequest()
        val pathBuilder = StringBuilder()

        with(downloadPreferences) {
            request.apply {
                addOption("download", url)

                pathBuilder.append(audioDownloadDir)
                pathBuilder.buildPathExtensions(downloadPreferences)

                Log.d(TAG, "Download path configured: $pathBuilder")

                addOption("--output", pathBuilder.toString())

                if (useCookies) useCookies()
                if (useYtMetadata) addOption("--ytm-data")
                if (dontFilter) addOption("--dont-filter-results")

                if (downloadPreferences.downloadLyrics && downloadPreferences.lyricProviders.isNotEmpty()) {
                    addOption("--lyrics")
                    if (downloadPreferences.lyricProviders.contains("Synced")) addOption("synced")
                    if (downloadPreferences.lyricProviders.contains("Genius")) addOption("genius")
                    if (downloadPreferences.lyricProviders.contains("Musixmatch")) addOption("musixmatch")
                    if (downloadPreferences.lyricProviders.contains("AZLyrics")) addOption("azlyrics")
                }

                if (sponsorBlock) addOption("--sponsor-block")
                if (onlyVerifiedResults) addOption("--only-verified-results")
                if (skipExplicit) addOption("--skip-explicit")
                if (generateLRC) addOption("--generate-lrc")
                if (skipAlbumArt) addOption("--skip-album-art")

                if (preserveOriginalAudio) {
                    addOption("--bitrate", "disable")
                    addAudioFormat()
                } else {
                    addAudioQuality()
                    addAudioFormat()
                }

                addAudioProvider(downloadPreferences)

                if (useSpotifyPreferences) {
                    if (spotifyClientID.isNotEmpty() && spotifyClientSecret.isNotEmpty()) {
                        addOption("--client-id", spotifyClientID)
                        addOption("--client-secret", spotifyClientSecret)
                    } else {
                        Log.w(TAG, "Custom Spotify credentials enabled but not provided. Falling back to default.")
                    }
                }
            }
        }
        return request
    }

    @CheckResult
    fun downloadSong(
        songInfo: SpotifySong,
        taskId: String,
        downloadPreferences: DownloadPreferences,
        progressCallback: ((Float, Long, String) -> Unit)?
    ): Result<List<String>> {
        if (songInfo.url.isBlank()) return Result.failure(Throwable(context.getString(R.string.fetch_info_error_msg)))

        val request = createDownloadRequest(songInfo.url, downloadPreferences)
        val pathBuilder = StringBuilder().append(audioDownloadDir).also { it.buildPathExtensions(downloadPreferences) }
        
        return runCatching {
            SpotDL.getInstance().execute(request, taskId, callback = progressCallback)
        }.fold(
            onSuccess = { response ->
                when {
                    response.output.contains("LookupError") -> Result.failure(Throwable("A LookupError occurred. The song wasn't found. Try changing the audio provider."))
                    response.output.contains("YT-DLP") -> Result.failure(Throwable("An error occurred with yt-dlp while downloading. Please report this issue."))
                    response.output.contains("HTTPError") -> Result.failure(Throwable("A HTTPError occurred. Try changing providers."))
                    response.output.contains("ReadTimeout") -> Result.failure(Throwable("A ReadTimeout occurred. Try changing providers."))
                    response.output.contains("ValueError") -> Result.failure(Throwable("A ValueError occurred. Try changing providers."))
                    response.output.contains("Skipping explicit song") -> Result.failure(Throwable("An explicit song has been skipped. Disable 'Skip explicit songs' in settings to download."))
                    else -> onFinishDownloading(
                        preferences = downloadPreferences,
                        songInfo = songInfo,
                        downloadPath = buildPathForDatabase(pathBuilder.toString(), songInfo)
                    )
                }
            },
            onFailure = { th ->
                th.printStackTrace()
                if (th.message?.contains("No such file or directory") == true) {
                    onFinishDownloading(
                        preferences = downloadPreferences,
                        songInfo = songInfo,
                        downloadPath = buildPathForDatabase(pathBuilder.toString(), songInfo)
                    )
                } else {
                    Result.failure(th)
                }
            }
        )
    }

    @CheckResult
    private fun onFinishDownloading(
        preferences: DownloadPreferences,
        songInfo: SpotifySong,
        downloadPath: String
    ): Result<List<String>> = preferences.run {
        if (incognitoMode) {
            Result.success(emptyList())
        } else if (sdcard) {
            Result.success(moveFilesToSdcard(
                sdcardUri = sdcardUri, tempPath = context.getSdcardTempDir(songInfo.song_id)
            ).apply {
                insertInfoIntoDownloadHistory(songInfo, this)
            })
        } else {
            Result.success(
                scanSongIntoDownloadHistory(
                    songInfo = songInfo,
                    downloadPath = downloadPath,
                )
            )
        }
    }

    @CheckResult
    private fun scanSongIntoDownloadHistory(
        songInfo: SpotifySong,
        downloadPath: String,
    ): List<String> = FilesUtil.scanFileToMediaLibraryPostDownload(
        title = songInfo.name, downloadDir = downloadPath
    ).apply {
        Log.d(TAG, "scanSongIntoDownloadHistory: $downloadPath")
        insertInfoIntoDownloadHistory(songInfo, this)
    }

    private fun insertInfoIntoDownloadHistory(
        songInfo: SpotifySong, filePaths: List<String>
    ) {
        filePaths.forEach { filePath ->
            val fullString = StringBuilder()
            fullString.append(songInfo.name)
            fullString.append(filePath)
            DatabaseUtil.insertInfo(
                DownloadedSongInfo(
                    id = createIntFromString(fullString.toString()),
                    songName = songInfo.name,
                    songAuthor = songInfo.artist,
                    songUrl = songInfo.url,
                    thumbnailUrl = songInfo.cover_url ?: "",
                    songPath = filePath,
                    songDuration = songInfo.duration ?: 0.0,
                    extractor = "Youtube Music",
                )
            )
        }
    }

    private fun createIntFromString(string: String): Int {
        var int = 0
        for (i in string.indices) {
            int += string[i].code
        }
        return int
    }

    fun executeParallelDownload(url: String, name: String) {
        val taskId = Downloader.makeKey(url, url.reversed())
        ToastUtil.makeToastSuspend(context.getString(R.string.download_started_msg))

        val downloadPreferences = DownloadPreferences()
        val request = createDownloadRequest(url, downloadPreferences).apply {
            addOption("--threads", downloadPreferences.threads.toString())
        }

        val isPlaylist = url.contains("playlist")

        Downloader.onProcessStarted()
        Downloader.onTaskStarted(url, name)
        
        runCatching {
            val response = SpotDL.getInstance().execute(
                request = request,
                processId = taskId,
                callback = { progress, _, text ->
                    NotificationsUtil.makeNotificationForParallelDownloads(
                        notificationId = taskId.hashCode(),
                        taskId = taskId,
                        progress = progress.roundToInt(),
                        text = text,
                        extraString = "$name - ${context.getString(R.string.parallel_download)}",
                        taskUrl = url,
                    )
                    Downloader.updateTaskOutput(
                        url = url, line = text, progress = progress, isPlaylist = isPlaylist
                    )
                })
            val finalResponse = removeDuplicateLines(clearLinesWithEllipsis(response.output))
            Downloader.onTaskEnded(url, finalResponse, name)
        }.onFailure {
            Log.d("Canceled?", "Exception: $it")
            it.printStackTrace()
            ToastUtil.makeToastSuspend(context.getString(R.string.download_error_msg))
            if (it is CanceledException) return@onFailure
            it.message.run {
                if (isNullOrEmpty()) Downloader.onTaskEnded(url)
                else Downloader.onTaskError(this, url)
            }
        }
        Downloader.onProcessEnded()
        ToastUtil.makeToastSuspend(context.getString(R.string.download_finished_msg))
    }

    fun clearLinesWithEllipsis(input: String): String {
        return input.split("\n").filterNot { it.contains("…") }.joinToString("\n")
    }

    fun removeDuplicateLines(input: String): String {
        return input.split("\n").distinct().joinToString("\n")
    }

    fun buildPathForDatabase(path: String, songInfo: SpotifySong = SpotifySong()): String {
        var newPath = path

        newPath = newPath.replace("\\{album\\}".toRegex(), songInfo.album_name)
        newPath = newPath.replace("\\{artist\\}".toRegex(), songInfo.artist)
        newPath = newPath.replace("\\{title\\}".toRegex(), songInfo.name)
        newPath = newPath.replace("\\{album-artist\\}".toRegex(), songInfo.album_artist)
        newPath = newPath.replace("\\{genre\\}".toRegex(), songInfo.genres?.joinToString() ?: "")
        newPath = newPath.replace("\\{year\\}".toRegex(), songInfo.year?.toString() ?: "0")
        newPath = newPath.replace("\\{output-ext\\}".toRegex(), getExtension() ?: "")

        return newPath
    }

    fun getExtension(): String? {
        val audioFormat = PreferencesUtil.getAudioFormat()
        return when (audioFormat) {
            0 -> "mp3"
            1 -> "flac"
            2 -> "ogg"
            3 -> "opus"
            4 -> "m4a"
            5 -> "wav"
            else -> null
        }
    }
}